import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar'
import React from 'react'
import { getPosts, getPostsMeta } from '@/lib/posts'
import { ThemeProvider } from '@/components/theme-provider'
import PostContextProvider from '@/components/posts-context'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const postsMeta = await getPostsMeta()

	return (
		<html lang='en'>
			<body>
				<ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
					<main className='flex justify-center mx-auto min-h-[calc(100vh-11rem)] mt-44'>
						<Navbar postsMeta={postsMeta} />
						<div className='max-w-[80ch] w-full  flex flex-col relative '>
							{children}
						</div>
					</main>
					<footer className='w-full h-20 mt-24 bg-gray-700'>footer yo</footer>
				</ThemeProvider>
			</body>
		</html>
	)
}
