import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body>
				<Navbar />
				<main>{children}</main>
				<footer className='w-full h-20 mt-52 bg-gray-700'>footer yo</footer>
			</body>
		</html>
	)
}
